language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpmd src/XlsxAppender/ xml design,naming,unusedcode,codesize,controversial
  - php ./vendor/bin/phpbench run ./benchmarks/ --config=./phpbench.json --report=default
